### ISSUE TITLE
Disconnected from the server

### ISSUE THREAD

**Issue by LoeliaBabin** [thomasdenecker/START-R#6]
I encounter some problems using START-R analyzer. When running the app I'm immediately disconnected from the server and analysis does not run. Did you ever have this problem ?  Is there any solutions ? 
Thanks

**Comment by thomasdenecker** [comment]
Hello,

When does the disconnection take place? At the time of starting the analysis (when the Run button is clicked)?

What is your operating system ? Could you tell me the error message in the log file (see the READ ME section [Launch in debug mode](https://github.com/thomasdenecker/START-R#launch-in-debug-mode))?

**Comment by LoeliaBabin** [comment]
Thank you for your fast answer.
Disconnection take place when the Run button is clicked, I'm working on Mac OS X High Sierra.  I tried to run in debug mode, but it seems there's no log file created.

**Comment by thomasdenecker** [comment]
One of the classic problems is related to the right to write. Did you authorize Docker to write?  You will find in the docker documentation how to do in the [File sharing section](https://docs.docker.com/docker-for-mac/).

Once you have added write permission to the START folder, restart the docker application and then START-R analyzer. Normally, the problem should be solved.

**Comment by LoeliaBabin** [comment]
I changed the File Sharing option and this time I obtained a log file, but analysis is still not working.

Here details of the log file :  


Attaching package: 'shinyjs'

The following object is masked from 'package:shiny':

    runExample

The following objects are masked from 'package:methods':

    removeClass, show

Note: the specification for S3 class "AsIs" in package 'BiocGenerics' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
Note: the specification for S3 class "connection" in package 'BiocGenerics' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
Note: the specification for S3 class "file" in package 'BiocGenerics' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
Note: the specification for S3 class "pipe" in package 'BiocGenerics' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
Note: the specification for S3 class "textConnection" in package 'BiocGenerics' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
Note: the specification for S3 class "AsIs" in package 'DBI' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
No methods found in "RSQLite" for requests: dbGetQuery
Welcome to SNPchip version 2.16.0
Loading required package: cluster
Loading required package: MASS
Warning: replacing previous import by 'shiny::validateCssUnit' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::br' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tags' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::div' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h1' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h2' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h3' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h4' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h5' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::h6' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::knit_print.html' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagSetChildren' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeScript' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::em' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagAppendChild' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::is.singleton' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeHTML' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeMarkdown' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::code' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagList' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::a' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagAppendAttributes' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::singleton' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::hr' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::p' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::suppressDependencies' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tagAppendChildren' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeText' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::pre' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::span' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::withTags' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::htmlTemplate' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::img' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::tag' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::includeCSS' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::knit_print.shiny.tag' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::knit_print.shiny.tag.list' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::strong' when loading 'crosstalk'
Warning: replacing previous import by 'shiny::HTML' when loading 'crosstalk'
Note: the specification for S3 class "AsIs" in package 'jsonlite' seems equivalent to one from package 'RJSONIO': not turning on duplicate class definitions for this class.
Note: the specification for S3 class "integer64" in package 'jsonlite' seems equivalent to one from package 'bit64': not turning on duplicate class definitions for this class.
Warning in rgl.init(initValue, onlyNULL) :
  RGL: unable to open X11 display
Warning: 'rgl_init' failed, running with rgl.useNULL = TRUE

This is package 'modeest' written by P. PONCET.
For a complete list of functions, use 'library(help = "modeest")' or 'help.start()'.

Note: the specification for S3 class "family" in package 'MatrixModels' seems equivalent to one from package 'lme4': not turning on duplicate class definitions for this class.

Attaching package: 'car'

The following object is masked from 'package:pracma':

    logit


Listening on http://127.0.0.1:36197
Warning in dir.create(date) :
  cannot create dir '20200903_1', reason 'Permission denied'
Warning: Error in setwd: cannot change working directory
Stack trace (innermost first):
    66: setwd
    65: observeEventHandler [/srv/shiny-server/app.R#1771]
     1: runApp

Execution halted

**Comment by thomasdenecker** [comment]
I thank you for the log file and I confirm that the problem comes from the writing rights :

`cannot create dir '20200903_1', reason 'Permission denied'`

Did you authorize Docker to write in the START-R folder (and all subfolders in particular START-R_analyzer > Outputs ) ?

**Comment by LoeliaBabin** [comment]
Thank you for your help, the problem was due to writing rights on the folder itself (only reading was authorized for all users). 
Now, analysis runs, but I think I have a problem with centromeres position file, I didn't find on the wiki the exact format for this file (I'm working with hg19 and not hg18). Do you have an example file ?

**Comment by thomasdenecker** [comment]
Thank you for your feedback. As I was telling you, the writing rights are the main cause of errors in the program. Once Docker has write permission, everything is back to normal.

Concerning the centromeres, in the application you have the following explanatory text:

*"You can enter your own centromere position file. It must be composed of 3 columns. The first must contain the names of the chromosomes. They must be strictly identical to those in your data files or they will be ignored (START-R will consider that there is no centromere). The second column corresponds to the beginning position of  the centromere and the third column to the end position."*

Does this explanation seem sufficient to you? If not, other users might have the same need as you and in this case I will add an example file.

Thank you again for your feedback.

**Comment by LoeliaBabin** [comment]
Thank you very very much for your help. 
Now it works, I had some troubles due to unknown chromosomes in my bam coverage file and header problem in my centromere position file. After removing all these things it works quite well.

**Comment by thomasdenecker** [comment]
With pleasure and thank you for your feedback.
